name: websocket_channel_wrapper
description: Wrapper for web_socket_channel package lightweight and isomorphic lib with socket.io-like event handling, Future-based requests.
version: 1.1.1
author: cTatu <cristian.tatu@estudiante.uam.es>
homepage: https://github.com/cTatu/ws-wrapper-dart2

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  web_socket_channel: ^1.0.14
  pedantic: ^1.8.0+1